### ISSUE TITLE
ImageMagick temp files filling disk space

### ISSUE THREAD

**Issue by kot0dama** [canonical/assets.ubuntu.com#210]
Image Magick temp files are filling disk space fast:
https://pastebin.canonical.com/p/FP2R97XMFX/ (sorry, Canonical link).

It seems the project is missing configuration to limit disk space usage for temp files as described on https://github.com/ImageMagick/ImageMagick/issues/395

**Comment by faebd7** [comment]
This is still happening. It causes these pods to consume excessive disk space, cause evictions, and trigger alerts on some of the k8s workers.

Details of the current state here (Canonical-only link): https://pastebin.canonical.com/p/Qss6G73wwT/

**Comment by goulinkh** [comment]
Sorry for the delay! I'm currently looking into this, it seems to be caused by the library ImageMagick where other people are having this issue as well: https://github.com/ImageMagick/ImageMagick/issues/395
I have a couple of ideas on how to solve this, even I don't manage to solve it using ImageMagick configurations I will add a cron job to perform cleanups every 30mins, this will be the last resort as it's not an ideal solution especially if we call the ImageMagick lib too often in a short amount of time.
